// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtWzYAt_uG2ad_g304N4lt-OOFhXdYxwU',
    appId: '1:115588830626:web:ff569f27f6dd5f4202cefb',
    messagingSenderId: '115588830626',
    projectId: 'gas-conference',
    authDomain: 'gas-conference.firebaseapp.com',
    storageBucket: 'gas-conference.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuAfn3EbC4XSFzbMt4fiGsvFsoEycJeN8',
    appId: '1:115588830626:android:719a77f5bb2edece02cefb',
    messagingSenderId: '115588830626',
    projectId: 'gas-conference',
    storageBucket: 'gas-conference.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUrsyDvGR-QFEMGIg9_rWTthAW3WU4Fe8',
    appId: '1:115588830626:ios:4eda775d534f9eac02cefb',
    messagingSenderId: '115588830626',
    projectId: 'gas-conference',
    storageBucket: 'gas-conference.appspot.com',
    iosBundleId: 'com.example.gasConference',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUrsyDvGR-QFEMGIg9_rWTthAW3WU4Fe8',
    appId: '1:115588830626:ios:6796267f6b58917d02cefb',
    messagingSenderId: '115588830626',
    projectId: 'gas-conference',
    storageBucket: 'gas-conference.appspot.com',
    iosBundleId: 'com.example.gasConference.RunnerTests',
  );
}
